package pz.klasywsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2018-06-22T17:44:03.189+02:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "TPSigningService", 
                  wsdlLocation = "https://int.pz.gov.pl/pz-services/tpSigning?wsdl",
                  targetNamespace = "http://signing.ws.comarch.gov") 
public class TPSigningService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://signing.ws.comarch.gov", "TPSigningService");
    public final static QName TPSigning = new QName("http://signing.ws.comarch.gov", "TPSigning");
    static {
        URL url = null;
        try {
            url = new URL("https://int.pz.gov.pl/pz-services/tpSigning?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TPSigningService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://int.pz.gov.pl/pz-services/tpSigning?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TPSigningService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TPSigningService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TPSigningService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TPSigningService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TPSigningService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TPSigningService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns TPSigning
     */
    @WebEndpoint(name = "TPSigning")
    public TPSigning getTPSigning() {
        return super.getPort(TPSigning, TPSigning.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TPSigning
     */
    @WebEndpoint(name = "TPSigning")
    public TPSigning getTPSigning(WebServiceFeature... features) {
        return super.getPort(TPSigning, TPSigning.class, features);
    }

}
