package pz.klasywsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2018-06-22T17:00:56.319+02:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://signing.ws.comarch.gov", name = "TPSigning")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface TPSigning {

    @WebMethod(action = "hasTrustedProfilePerson")
    @WebResult(name = "hasTrustedProfilePersonReturn", targetNamespace = "http://signing.ws.comarch.gov", partName = "hasTrustedProfilePersonReturn")
    public boolean hasTrustedProfilePerson(
        @WebParam(partName = "tgsid", name = "tgsid")
        java.lang.String tgsid
    ) throws WSSigningException_Exception;

    @WebMethod(action = "addDocumentToSigning")
    @WebResult(name = "addDocumentToSigningReturn", targetNamespace = "http://signing.ws.comarch.gov", partName = "addDocumentToSigningReturn")
    public java.lang.String addDocumentToSigning(
        @WebParam(partName = "doc", name = "doc")
        byte[] doc,
        @WebParam(partName = "successURL", name = "successURL")
        java.lang.String successURL,
        @WebParam(partName = "failureURL", name = "failureURL")
        java.lang.String failureURL,
        @WebParam(partName = "additionalInfo", name = "additionalInfo")
        java.lang.String additionalInfo
    ) throws WSSigningException_Exception;

    @WebMethod(action = "verifySignedDocument")
    @WebResult(name = "verifySignedDocumentReturn", targetNamespace = "http://signing.ws.comarch.gov", partName = "verifySignedDocumentReturn")
    public java.lang.String verifySignedDocument(
        @WebParam(partName = "document", name = "document")
        byte[] document
    ) throws WSSigningException_Exception;

    @WebMethod(action = "getSignedDocument")
    @WebResult(name = "getSignedDocumentReturn", targetNamespace = "http://signing.ws.comarch.gov", partName = "getSignedDocumentReturn")
    public byte[] getSignedDocument(
        @WebParam(partName = "id", name = "id")
        java.lang.String id
    ) throws WSSigningException_Exception;

    @WebMethod(action = "hasTrustedProfileInstitution")
    @WebResult(name = "hasTrustedProfileInstitutionReturn", targetNamespace = "http://signing.ws.comarch.gov", partName = "hasTrustedProfileInstitutionReturn")
    public boolean hasTrustedProfileInstitution(
        @WebParam(partName = "tgsid", name = "tgsid")
        java.lang.String tgsid
    ) throws WSSigningException_Exception;
}
