
package pz.klasywsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.6
 * 2018-06-22T17:00:56.299+02:00
 * Generated source version: 2.7.6
 */

@WebFault(name = "WSSigningException", targetNamespace = "http://exception.ws.comarch.gov")
public class WSSigningException_Exception extends Exception {
    
    private pz.klasywsdl.WSSigningException wsSigningException;

    public WSSigningException_Exception() {
        super();
    }
    
    public WSSigningException_Exception(String message) {
        super(message);
    }
    
    public WSSigningException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public WSSigningException_Exception(String message, pz.klasywsdl.WSSigningException wsSigningException) {
        super(message);
        this.wsSigningException = wsSigningException;
    }

    public WSSigningException_Exception(String message, pz.klasywsdl.WSSigningException wsSigningException, Throwable cause) {
        super(message, cause);
        this.wsSigningException = wsSigningException;
    }

    public pz.klasywsdl.WSSigningException getFaultInfo() {
        return this.wsSigningException;
    }
}
